services:
  db:
    image: postgres:15
    restart: always
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: fadesp_db
    ports:
      - "5440:5432"
    volumes:
      - db_data:/var/lib/postgresql/data

volumes:
  db_data:

